const KEY='echelon-controls-v2';
export const touchDefaults={ 'move-pad':[15,78], 'touch-fire':[87,51], 'touch-aim':[74,43], 'touch-jump':[91,73], 'touch-hack':[66,76], 'touch-reload':[78,86], 'touch-emp':[61,89], 'touch-sprint':[15,56], 'touch-fire-left':[9,42] };
export function loadControls(){let saved;try{saved=JSON.parse(localStorage.getItem(KEY));}catch{}return {profile:['auto','desktop','remote','touch'].includes(saved?.profile)?saved.profile:'auto',mouse:clamp(saved?.mouse,.2,2.5,1),touch:clamp(saved?.touch,.2,2.5,1),ads:clamp(saved?.ads,.2,1,.55),size:clamp(saved?.size,.75,1.3,1),opacity:clamp(saved?.opacity,.3,1,.68),layout:['classic','left-fire','custom'].includes(saved?.layout)?saved.layout:'classic',positions:saved?.positions||{}};}
function clamp(v,min,max,fallback){return Number.isFinite(Number(v))?Math.max(min,Math.min(max,Number(v))):fallback;}
export function initialInput(settings){return settings.profile==='touch'||settings.profile==='auto'&&matchMedia('(pointer: coarse)').matches&&!matchMedia('(any-pointer: fine)').matches?'touch':settings.profile==='remote'?'remote':'desktop';}
export function createControlSettings({onChange,onOpen,onClose}){const settings=loadControls(),panel=document.getElementById('controls-panel'),$=id=>document.getElementById(id);let editing=false,drag=null;
 const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(settings));}catch{}apply();onChange(settings);};
 function apply(){document.body.dataset.touchLayout=settings.layout;document.documentElement.style.setProperty('--control-scale',settings.size);document.documentElement.style.setProperty('--control-opacity',settings.opacity);for(const [id,base]of Object.entries(touchDefaults)){const custom=settings.layout==='custom'?settings.positions[id]:null;const p=Array.isArray(custom)?custom:base,el=$(id);let x=clamp(p[0],6,94,base[0]),y=clamp(p[1],20,90,base[1]);const w=el.offsetWidth||64,h=el.offsetHeight||64;x=Math.max(w/2/innerWidth*100+1,Math.min(99-w/2/innerWidth*100,x));y=Math.max(70/innerHeight*100+h/2/innerHeight*100,Math.min(98-h/2/innerHeight*100,y));el.style.left=x+'%';el.style.top=y+'%';}for(const [key,id]of Object.entries({profile:'input-profile',mouse:'mouse-sensitivity',touch:'touch-sensitivity',ads:'ads-sensitivity',size:'control-size',opacity:'control-opacity',layout:'touch-layout'}))$(id).value=settings[key];}
 $('controls-button').onclick=()=>{onOpen();panel.hidden=false;apply();};$('controls-close').onclick=()=>{panel.hidden=true;onClose();};
 for(const [key,id]of Object.entries({profile:'input-profile',mouse:'mouse-sensitivity',touch:'touch-sensitivity',ads:'ads-sensitivity',size:'control-size',opacity:'control-opacity',layout:'touch-layout'}))$(id).addEventListener('input',e=>{settings[key]=['profile','layout'].includes(key)?e.target.value:Number(e.target.value);persist();});
 $('edit-hud').onclick=()=>{editing=true;panel.hidden=true;document.body.classList.add('editing-hud','touch-mode');$('touch-controls').hidden=false;$('hud-editor').hidden=false;apply();};
 $('save-hud').onclick=()=>{editing=false;drag=null;document.body.classList.remove('editing-hud');$('hud-editor').hidden=true;$('touch-controls').hidden=true;panel.hidden=false;persist();};
 $('reset-hud').onclick=()=>{settings.positions={};settings.layout='classic';persist();};
 for(const id of Object.keys(touchDefaults)){const el=$(id);el.addEventListener('pointerdown',e=>{if(!editing)return;e.preventDefault();e.stopImmediatePropagation();drag={id,pointer:e.pointerId};el.setPointerCapture(e.pointerId);},true);el.addEventListener('pointermove',e=>{if(!editing||drag?.id!==id||drag.pointer!==e.pointerId)return;e.preventDefault();settings.layout='custom';settings.positions[id]=[e.clientX/innerWidth*100,e.clientY/innerHeight*100];apply();},true);for(const event of ['pointerup','pointercancel'])el.addEventListener(event,()=>{if(drag?.id===id)drag=null;});}
 window.addEventListener('resize',apply);apply();return {settings,apply,get editing(){return editing;}};
}
