import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
const points={market:[-49,40],transit:[49,10],civic:[49,-80]};
export async function buildDistricts(scene,world){
 const loader=new GLTFLoader(),assets={},groups=[],interactables=[],cameras=[],gates=[],effects=[],lights=[],sectors={},contracts={},visited=new Set();let observer=new T.Vector3(0,1.85,61),quality='balanced',time=0;
 const interiorWall=world.mats.concrete.clone();interiorWall.color.set(0xaebfc1);const interiorFloor=world.mats.pavement.clone();interiorFloor.color.set(0x71838b);
 const material=(c,emit=0)=>new T.MeshStandardMaterial({color:c,metalness:.4,roughness:.4,emissive:c,emissiveIntensity:emit});
 const ceramic=material(0x748f98),dark=material(0x172f39),cyan=material(0x62edeb,1),amber=material(0xffb64c,1),red=material(0xff4f43,1),green=material(0x8cf6b0,1);
 function merge(root){root.updateMatrixWorld(true);const mats=new Map(),g=new T.Group();root.traverse(m=>{if(m.isMesh){let geo=m.geometry.clone().applyMatrix4(m.matrixWorld).toNonIndexed();geo.deleteAttribute('tangent');if(!geo.attributes.uv)geo.setAttribute('uv',new T.BufferAttribute(new Float32Array(geo.attributes.position.count*2),2));const mat=m.material.name.startsWith('Architectural ceramic')?interiorWall:m.material.name.startsWith('Composite flooring')?interiorFloor:m.material;const list=mats.get(mat)||[];list.push(geo);mats.set(mat,list);}});for(const [mat,gs]of mats){const m=new T.Mesh(mergeGeometries(gs),mat);m.castShadow=m.receiveShadow=true;g.add(m);gs.forEach(x=>x.dispose());}return g;}
 await Promise.all(['clinic-module','transit-module','survivor-pod','salvage-cache','mission-console'].map(async n=>assets[n]=merge((await loader.loadAsync(`/assets/neon/${n}.glb`)).scene)));
 function block(root,x,y,z,w,h,d,mat=ceramic,solid=false){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);root.add(m);m.castShadow=m.receiveShadow=true;if(solid)world.obstacles.push({x,z,w:w/2+.35,d:d/2+.35,minY:y-h/2,maxY:y+h/2});return m;}
 function label(root,text,x,y,z,angle=0,color='#adf2e9',width=6){const c=document.createElement('canvas');c.width=768;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#102d39';ctx.fillRect(0,0,768,128);ctx.fillStyle=color;ctx.font='bold 42px sans-serif';ctx.textAlign='center';ctx.fillText(text,384,80);const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(width,1),new T.MeshBasicMaterial({map}));m.position.set(x,y,z);m.rotation.y=angle;root.add(m);return m;}
 function prop(root,name,x,y,z,rotation=0){const g=assets[name].clone();g.position.set(x,y,z);g.rotation.y=rotation;root.add(g);return g;}
 function point(kind,id,name,x,y,z,extra={}){const g=prop(scene,kind==='cache'?'salvage-cache':'mission-console',x,y,z);const ring=new T.Mesh(new T.RingGeometry(.7,.78,32),new T.MeshBasicMaterial({color:kind==='cache'?0xffc66a:0x6dfff2,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,y+.15,z);scene.add(ring);const p={kind,id,name,position:new T.Vector3(x,y+1.2,z),g,ring,...extra};interactables.push(p);return p;}
 function room(name,x,z,rotation,title){const group=new T.Group();scene.add(group);group.add(prop(new T.Group(),name,0,0,0));group.position.set(x,0,z);group.rotation.y=rotation;
 // Authored wall geometry and colliders share the same local transforms. Door is always 4m wide.
 const walls=[[0,6,12,.2],[6,0,.2,12],[-6,0,.2,12],[-4,-6,4,.2],[4,-6,4,.2]];
 for(const [lx,lz,w,d]of walls){const v=new T.Vector3(lx,0,-lz).applyAxisAngle(new T.Vector3(0,1,0),rotation);const swapped=Math.abs(Math.sin(rotation))>.5;world.obstacles.push({x:x+v.x,z:z+v.z,w:(swapped?d:w)/2+.3,d:(swapped?w:d)/2+.3,minY:0,maxY:4});}
 label(group,title,0,3.3,6.15,0,'#abf2e9',10);const lamp=new T.PointLight(0xa5e9ff,18,15,2);lamp.position.set(x,3,z);scene.add(lamp);lamp.userData.district=x<0?'market':'transit';lights.push(lamp);groups.push({group,x,z,permanent:true});return group;}
 room('clinic-module',-49,40,Math.PI/2,'KAIROS / MEDICAL WING');room('transit-module',49,10,-Math.PI/2,'TRANSIT / SIGNAL ARCHIVE');
 point('signal','transit-signal','Trace Mara’s signal',50,0,10);
 point('choice','clinic-choice','Life support terminal',-49,0,40);
 const pod=prop(scene,'survivor-pod',-52,0,42,Math.PI/2);
 point('upgrade','workbench','Upgrade workbench',-49,0,35);
 label(scene,'← MEDICAL WING',-14,2.7,40,0,'#9be8eb',5);label(scene,'SIGNAL ARCHIVE →',14,2.7,10,0,'#ffcf82',5);
 // A walkable service ramp climbs to a roof terrace. Slope and floor height are deterministic.
 const roof=new T.Group();scene.add(roof);block(roof,-49,5.85,0,16,.3,20);for(const x of [-57,-41])block(roof,x,6.5,0,.15,1,20,ceramic,true);block(roof,-49,6.5,-10,16,1,.15,ceramic,true);
 const ramp=block(roof,-49,2.9,20,4,.2,Math.sqrt(436));ramp.rotation.x=Math.atan2(6,20);
 for(const x of [-51.1,-46.9]){const rail=block(roof,x,3.8,20,.12,.12,Math.sqrt(436));rail.rotation.x=Math.atan2(6,20);}
 for(let z=12;z<30;z+=3)block(roof,-49,(30-z)*.3+.08,z,3.8,.03,.1,cyan);
 label(scene,'ROOFTOP ACCESS',-49,2,29,0,'#a3f7e6',5);point('recording','roof-record','Recording: The first awakening',-49,6,-5,{text:'ARCHIVE 07: We taught the city to protect us. Nobody asked who it would protect us from.'});
 point('cache','roof-cache','Rooftop salvage',-53,6,3);point('cache','clinic-cache','Medical supplies',-53,0,36);point('cache','transit-cache','Transit salvage',53,0,14);point('recording','market-record','Recording: Last train',-15,0,39,{text:'STATION LOG: The last train left empty. Every passenger received the same message: stay home. The doors never reopened.'});
 // Cameras sweep visible ground cones; relay shutdown disables each district pair.
 for(let i=0;i<6;i++){const district=['market','transit','civic'][Math.floor(i/2)],x=i%2?12:-12,z=30-Math.floor(i/2)*53,g=new T.Group();g.position.set(x,4,z);scene.add(g);block(g,0,0,0,.55,.25,.35,dark);const eye=new T.Mesh(new T.SphereGeometry(.09,12,8),red.clone());eye.position.z=.22;g.add(eye);const cone=new T.Mesh(new T.ConeGeometry(5,16,24,1,true),new T.MeshBasicMaterial({color:0x7ee8dc,transparent:true,opacity:.012,depthWrite:false,side:T.DoubleSide}));cone.rotation.x=-Math.PI/2;cone.position.z=8;g.add(cone);cameras.push({g,eye,cone,district,phase:i,disabled:false,forward:new T.Vector3()});}
 for(let i=0;i<3;i++){const z=17-i*53,g=new T.Group();scene.add(g);const left=block(g,-10.5,1,z,.35,2,.4,dark),right=block(g,10.5,1,z,.35,2,.4,dark);const beam=block(g,0,.8,z,18,1.6,.16,red.clone());beam.visible=false;const collider={x:0,z,w:9.35,d:.5,minY:0,maxY:1.7,disabled:true};world.obstacles.push(collider);label(g,'SERVICE PASSAGES REMAIN OPEN',0,2.6,z+.1,0,'#ffbe81',8);gates.push({g,beam,collider,z,district:['market','transit','civic'][i],closed:false,until:0,activateAt:0});}
 function surface(x,z){if(x>=-57&&x<=-41&&z>=-10&&z<=10)return 6;if(x>=-51&&x<=-47&&z>10&&z<=30)return(30-z)*.3;return 0;}
 function prepareSector(district,theme){if(sectors[district])return;const i=['market','transit','civic'].indexOf(district),x=i===0?-49:49,z=i===0?-40:i===1?-40:-110;const g=new T.Group();g.position.set(x,0,z);scene.add(g);const detail=new T.Group();g.add(detail);const accent=theme==='medical'?cyan:theme==='courier'?amber:green;
 block(detail,0,.08,0,14,.16,16,dark);for(const side of [-1,1]){block(detail,side*6,1.8,0,.2,3.6,14,ceramic);block(detail,side*5.8,3.4,0,.08,.1,13,accent);for(let n=-5;n<=5;n+=5)prop(detail,'salvage-cache',side*4.5,0,n);}
 if(theme==='medical'){prop(detail,'survivor-pod',-4,0,0);prop(detail,'survivor-pod',4,0,0);}else if(theme==='courier'){for(const x of [-4.5,4.5])for(const z of [-3,3])block(detail,x,1.6,z,2.3,3.2,2.3,ceramic);block(detail,0,4.4,0,13,.25,3,amber);}else{for(const x of [-4.5,4.5]){prop(detail,'mission-console',x,0,0);block(detail,x,3.8,0,.08,7.6,.08,ceramic);}block(detail,0,4.8,-3,12,.08,5,dark);}
 label(detail,theme==='medical'?'RELIEF / FIELD CLINIC':theme==='courier'?'COURIER / DEAD DROP':'RESISTANCE / SAFE PASSAGE',0,3.8,-6,0,'#bef4e9',12);
 const lod=new T.LOD();g.remove(detail);lod.addLevel(detail,0);const far=new T.Group();block(far,0,1.7,0,14,3.4,16,dark);lod.addLevel(far,85);g.add(lod);
 // Geometry is confined to reserved pockets, with a clear 8m center aisle and no mission blockers.
 for(const side of [-1,1])world.obstacles.push({x:x+side*6,z,w:.45,d:7.3,minY:0,maxY:3.6});
 const p=point('cache','sector-'+district,theme==='medical'?'Field medicine':theme==='courier'?'Courier cache':'Resistance salvage',x,0,z,{sector:district,theme});sectors[district]={district,theme,x,z,g,p,visited:false};if(contracts[district])assignContract(district,contracts[district]);groups.push({group:g,x,z});return sectors[district];}
 let pending=[];
 function assignContract(district,type){contracts[district]=type;const sector=sectors[district];if(sector){sector.p.kind='contract';sector.p.contract=type;sector.p.name=type==='recover'?'Recover the courier’s dead drop':type==='rescue'?'Stabilize the field clinic patient':'Sabotage the surveillance repeater';}}
 function applyPlan(plan){for(const a of plan.actions){if(a.type==='mission'){assignContract(a.district,a.value);if(!sectors[a.district]&&!pending.some(p=>p.district===a.district))pending.push({district:a.district,value:a.value==='rescue'?'medical':a.value==='recover'?'courier':'resistance'});}if(a.type==='sector'&&!sectors[a.district]&&!pending.some(p=>p.district===a.district))pending.push(a);if(a.type==='route'){const gate=gates.find(g=>g.district===a.district);const relay=world.relays[['market','transit','civic'].indexOf(a.district)];gate.closed=a.value==='lockdown'&&!relay.done;gate.until=time+35;gate.activateAt=time+2;}if(a.type==='power'){for(const l of [...lights,...world.streetLights])if(l.userData.district===a.district)l.intensity=a.value==='dim'?5:(lights.includes(l)?18:36);const i=['market','transit','civic'].indexOf(a.district);cameras.filter(c=>c.district===a.district).forEach(c=>c.cone.material.opacity=a.value==='dim'?.006:.012);}}}
 function update(t,dt,position,currentQuality){time=t;observer.copy(position);quality=currentQuality;
 if(pending.length){const a=pending[0],i=['market','transit','civic'].indexOf(a.district),x=i===0?-49:49,z=i===0?-40:i===1?-40:-110;if(Math.hypot(position.x-x,position.z-z)>25){pending.shift();prepareSector(a.district,a.value);}}
 for(const sector of Object.values(sectors)){const distance=Math.hypot(position.x-sector.x,position.z-sector.z);sector.g.visible=distance<125;if(distance<20){sector.visited=true;visited.add(sector.district);}}
 for(const c of cameras){const i=['market','transit','civic'].indexOf(c.district);c.disabled=world.relays[i].done||t<(c.stunUntil||0);c.g.rotation.y=(c.g.position.x<0?Math.PI/2:-Math.PI/2)+Math.sin(t*.3+c.phase)*.6;c.cone.visible=!c.disabled;c.eye.material.color.set(c.disabled?0x294746:0xff6651);c.forward.set(0,0,1).applyQuaternion(c.g.quaternion);}
 for(const gate of gates){if(world.relays[['market','transit','civic'].indexOf(gate.district)].done||t>gate.until)gate.closed=false;const occupied=Math.abs(position.x)<9.7&&Math.abs(position.z-gate.z)<1.2;gate.collider.disabled=!gate.closed||occupied||t<gate.activateAt;gate.beam.visible=gate.closed&&(t>gate.activateAt||Math.sin(t*12)>0);if(gate.closed)for(const car of world.traffic){const dz=gate.z-car.g.position.z;if(Math.abs(dz)<13&&dz*car.speed>0&&t>(car.reroutedUntil||0)){car.speed*=-1;car.g.rotation.y+=Math.PI;car.reroutedUntil=t+20;}}}
 for(const p of interactables){p.ring.material.opacity=.6+Math.sin(t*2)*.2;p.ring.material.transparent=true;}
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;e.m.position.addScaledVector(e.v,dt);e.v.y-=dt*5;e.m.material.opacity=Math.max(0,e.life*2);if(e.life<=0){scene.remove(e.m);e.m.geometry.dispose();e.m.material.dispose();effects.splice(i,1);}}
 }
 function impact(at,color=0xffd080){for(let i=0;i<8;i++){const m=new T.Mesh(new T.SphereGeometry(.035,4,3),new T.MeshBasicMaterial({color,transparent:true}));m.position.copy(at);scene.add(m);effects.push({m,v:new T.Vector3((Math.random()-.5)*4,Math.random()*3,(Math.random()-.5)*4),life:.35+Math.random()*.3});}}
 return {interactables,cameras,gates,sectors,contracts,assignContract,pod,surface,prepareSector,applyPlan,update,impact,visited,lights};
}
