import {inWorld} from './shared/roaming.js';
import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {CAST,NPC_IDS,available,castSnapshot,validateCastPlan,fallbackCast} from './shared/cast.js';
export async function buildCast(scene,world,{getCampaign,getPlayer,getStats,getSurface=()=>0,onLine,onEvent,onHelp,request}){
 function batchNode(root){root.updateWorldMatrix(true,true);const inverse=root.matrixWorld.clone().invert(),groups=new Map();for(const mesh of [...root.children]){if(!mesh.isMesh||Array.isArray(mesh.material))continue;const k=mesh.material.uuid;if(!groups.has(k))groups.set(k,{material:mesh.material,geometries:[],meshes:[]});const bucket=groups.get(k);bucket.geometries.push(mesh.geometry.clone().applyMatrix4(new T.Matrix4().multiplyMatrices(inverse,mesh.matrixWorld)));bucket.meshes.push(mesh);}for(const b of groups.values()){if(b.meshes.length<2)continue;const geometry=mergeGeometries(b.geometries);if(!geometry)continue;for(const m of b.meshes)root.remove(m);const mesh=new T.Mesh(geometry,b.material);root.add(mesh);}}
 const loader=new GLTFLoader(),actors=[];const models=await Promise.all(NPC_IDS.map(id=>loader.loadAsync('/assets/npc-'+id+'.glb')));
 for(let i=0;i<NPC_IDS.length;i++){const id=NPC_IDS[i],spec=CAST[id],g=models[i].scene;for(const joint of ['Head','Arm_L','Arm_R','Leg_L','Leg_R']){const node=g.getObjectByName(joint);if(node)batchNode(node);}batchNode(g);g.position.fromArray(spec.home);g.traverse(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;}});scene.add(g);
 const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const ctx=canvas.getContext('2d');ctx.fillStyle='#12323bcc';ctx.fillRect(0,0,512,96);ctx.textAlign='center';ctx.fillStyle='#dcedcc';ctx.font='bold 29px sans-serif';ctx.fillText(spec.name,256,37);ctx.fillStyle='#b1ceca';ctx.font='19px monospace';ctx.fillText(spec.role,256,72);const texture=new T.CanvasTexture(canvas),label=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:true}));label.scale.set(2.5,.47,1);label.position.y=2.17;g.add(label);
 const ring=new T.Mesh(new T.RingGeometry(.4,.44,24),new T.MeshBasicMaterial({color:spec.color,side:T.DoubleSide,transparent:true,opacity:.7}));ring.rotation.x=-Math.PI/2;ring.position.y=.018;g.add(ring);
 actors.push({id,g,label,ring,arms:['L','R'].map(s=>g.getObjectByName('Arm_'+s)),legs:['L','R'].map(s=>g.getObjectByName('Leg_'+s)),home:new T.Vector3(...spec.home),target:null,path:[],nextPath:0,lastAction:-100,lastWander:-100,phase:i*1.7,moving:false});
 }
 let initialized=false,busy=false,lastThink=-Infinity,revision=0,source='local',lastSpeech=0,clock=0;
 function canWalk(x,z){return inWorld(x,z)&&getSurface(x,z)<.15&&!world.obstacles.some(o=>!o.disabled&&(o.maxY===undefined||o.maxY>.3)&&Math.abs(x-o.x)<o.w+.2&&Math.abs(z-o.z)<o.d+.2);}
 // A bounded ground grid finds street/door routes instead of walking through walls.
 function route(from,to){const step=2,start=[Math.round(from.x/step),Math.round(from.z/step)],goal=[Math.round(to.x/step),Math.round(to.z/step)],key=(x,z)=>x+','+z,q=[start],seen=new Map([[key(...start),null]]);let head=0,best=start,bestD=Infinity;while(head<q.length&&head<7500){const a=q[head++],d=Math.hypot(a[0]-goal[0],a[1]-goal[1]);if(d<bestD){bestD=d;best=a;}if(d<1.5)break;for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=a[0]+dx,nz=a[1]+dz,k=key(nx,nz);if(seen.has(k)||!canWalk(nx*step,nz*step)||!canWalk((nx+a[0])*step/2,(nz+a[1])*step/2))continue;seen.set(k,a);q.push([nx,nz]);}}const path=[];let a=best;while(a&&seen.get(key(...a))){path.unshift(new T.Vector3(a[0]*step,0,a[1]*step));a=seen.get(key(...a));}return path;}
 function restore(){const c=getCampaign();for(const a of actors){const n=c.story.cast[a.id],p=new T.Vector3(...n.position);a.g.position.copy(canWalk(p.x,p.z)?p:a.home);a.path=[];a.target=null;}revision=0;initialized=true;}
 async function think(interaction=null){if(busy||!interaction&&Date.now()-lastThink<75000)return null;busy=true;lastThink=Date.now();const c=getCampaign(),s=castSnapshot(c,getStats());let plan;try{plan=await request({snapshot:s,interaction});const now=getCampaign();if(plan.context&&(plan.context.choice!==now.choice||plan.context.signal!==now.signal))return null;if(!validateCastPlan(plan,s))throw new Error('Invalid cast');source=plan.source; }catch{plan={...fallbackCast(castSnapshot(getCampaign(),getStats()),interaction),source:'local',revision:revision+1};source='local';}finally{busy=false;}
 if(getCampaign().completed||!interaction&&plan.revision<=revision)return null;revision=Math.max(revision+1,plan.revision||0);const current=getCampaign();current.story.npcRevision=revision;
 for(const n of plan.characters){if(!available(n.id,current))continue;const state=current.story.cast[n.id];state.goal=n.goal;state.mood=n.mood;state.memory.push(n.line);state.memory=state.memory.slice(-6);const a=actors.find(a=>a.id===n.id);a.target=null;a.path=[];if(interaction||a.g.position.distanceTo(getPlayer())<20&&clock-lastSpeech>18){onLine(n.line,CAST[n.id].name.toUpperCase());lastSpeech=clock;}}
 onEvent();return plan;
 }
 function update(t,dt,active){clock=t;if(!initialized)restore();const c=getCampaign(),player=getPlayer(),stats=getStats();for(const a of actors){const n=c.story.cast[a.id];const present=available(a.id,c),dist=a.g.position.distanceTo(player);a.g.visible=present&&dist<95;if(!present)continue;a.label.visible=dist<22;a.ring.visible=dist<10;if(!active)continue;const goal=n.goal;
 let dest=null;if((goal==='follow'||goal==='assist')&&dist>3.8&&player.y<3)dest=player.clone();else if(goal==='hide'||goal==='cover'){const threats=world.drones.filter(d=>d.hp>0&&d.g.position.distanceTo(a.g.position)<25);if(threats.length){const side=a.g.position.x>=0?1:-1;dest=new T.Vector3(side*18,0,a.g.position.z+5);}}else if((goal==='scavenge'||goal==='observe')&&t-a.lastWander>12){a.lastWander=t;dest=a.home.clone().add(new T.Vector3(Math.sin(t*.13+a.phase)*4,0,Math.cos(t*.11+a.phase)*5));}
 if(dest&&t>a.nextPath&&(!a.target||!a.path.length||a.target.distanceTo(dest)>3)){a.target=dest;a.path=route(a.g.position,dest);a.nextPath=t+3;}
 a.moving=false;if(a.path.length){const p=a.path[0],v=p.clone().sub(a.g.position);v.y=0;if(v.length()<.3)a.path.shift();else{v.normalize().multiplyScalar(Math.min(v.length(),dt*(goal==='cover'||goal==='hide'?2.4:1.55)));const nx=a.g.position.x+v.x,nz=a.g.position.z+v.z;if(canWalk(nx,nz)){a.g.position.x=nx;a.g.position.z=nz;a.g.rotation.y=Math.atan2(v.x,v.z);a.moving=true;}else{a.path=[];a.target=null;}}}else if(dist<7)a.g.rotation.y=Math.atan2(player.x-a.g.position.x,player.z-a.g.position.z);
 const swing=a.moving?Math.sin(t*8+a.phase)*.43:Math.sin(t*1.4+a.phase)*.025;for(let i=0;i<2;i++){if(a.arms[i])a.arms[i].rotation.x=swing*(i?1:-1);if(a.legs[i])a.legs[i].rotation.x=swing*(i?-1:1);}n.position=a.g.position.toArray();
 if(t-a.lastAction>35&&n.trust>=1){if(goal==='assist'&&dist<4&&stats.health<90){a.lastAction=t;n.helped++;onHelp('heal',a);onLine('Hold still. I can patch that up.',CAST[a.id].name.toUpperCase());}
 else if(goal==='cover'){const enemy=world.drones.find(d=>d.hp>0&&d.g.position.distanceTo(a.g.position)<17);if(enemy){a.lastAction=t;n.helped++;onHelp('cover',a,enemy);}}
 else if(goal==='scavenge'&&n.helped<3&&t-a.lastAction>65){a.lastAction=t;n.helped++;onHelp('salvage',a);onLine('Found a usable cell. Yours, this time.',CAST[a.id].name.toUpperCase());}}
 }for(const car of world.traffic)car.pedestrianStop=actors.some(a=>available(a.id,c)&&Math.abs(a.g.position.x-car.g.position.x)<2.4&&Math.abs(a.g.position.z-car.g.position.z)<7);if(active)think();}
 return {actors,update,restore,think,command:(id,goal)=>{getCampaign().story.cast[id].goal=goal;const a=actors.find(a=>a.id===id);a.path=[];a.target=null;onEvent();},nearest:()=>actors.filter(a=>a.g.visible&&a.g.position.distanceTo(getPlayer())<3.6).sort((a,b)=>a.g.position.distanceTo(getPlayer())-b.g.position.distanceTo(getPlayer()))[0],getState:()=>({source,busy,revision,actors:actors.map(a=>({id:a.id,visible:a.g.visible,position:a.g.position.toArray(),moving:a.moving,goal:getCampaign().story.cast[a.id].goal}))})};
}
