import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {DESTINATIONS,EXPANDED_BOUNDS} from './shared/roaming.js';
export function buildOpenCity(scene,world){
 world.bounds={...EXPANDED_BOUNDS};const chunks=[],crowd=[],pois=[],powerLamps=[],root=new T.Group();scene.add(root);const mats=world.mats;let seed=9102;const rnd=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646;};
 function box(x,y,z,w,h,d,mat,solid=false,parent=root){const geo=new T.BoxGeometry(w,h,d);if(mat.map){const uv=geo.attributes.uv,pos=geo.attributes.position,n=geo.attributes.normal;for(let i=0;i<uv.count;i++){const nx=Math.abs(n.getX(i)),ny=Math.abs(n.getY(i));uv.setXY(i,(nx>.5?pos.getZ(i):pos.getX(i))/6,(ny>.5?pos.getZ(i):pos.getY(i))/6);}}const m=new T.Mesh(geo,mat);m.position.set(x,y,z);parent.add(m);if(solid)world.obstacles.push({x,z,w:w/2+.45,d:d/2+.45,maxY:y+h/2,minY:y-h/2});return m;}
 box(0,-.16,250,470,.25,350,mats.pavement);for(const x of [-150,0,150]){box(x,-.012,250,24,.04,350,mats.road);for(let z=84;z<418;z+=10)box(x,.016,z,.18,.02,5,mats.yellow);}
 for(const z of [100,170,300,395]){box(0,-.006,z,450,.04,24,mats.road);for(let x=-214;x<220;x+=10)box(x,.024,z,5,.02,.18,mats.yellow);}
 function sign(name,x,z,color){const c=document.createElement('canvas');c.width=1024;c.height=256;const q=c.getContext('2d');q.fillStyle='#123441';q.fillRect(0,0,1024,256);q.strokeStyle=color;q.lineWidth=9;q.strokeRect(8,8,1008,240);q.fillStyle=color;q.textAlign='center';q.font='bold 70px sans-serif';q.fillText(name.toUpperCase(),512,116);q.font='24px monospace';q.fillText('NEW CARTHAGE / PUBLIC ACCESS',512,184);const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;const mesh=new T.Mesh(new T.PlaneGeometry(16,4),new T.MeshBasicMaterial({map}));mesh.position.set(x,6,z);scene.add(mesh);const reverse=mesh.clone();reverse.rotation.y=Math.PI;reverse.position.z-=.04;scene.add(reverse);}
 // City architecture and its colliders come from the shared Blender kit.
 for(const x of [-150,0,150])for(const side of [-1,1]){box(x+side*12.6,.08,250,.5,.16,350,mats.trim);for(let z=112;z<420;z+=32){box(x+side*14.5,2.8,z,.18,5.6,.18,mats.trim);box(x+side*13.5,5.6,z,2.3,.15,.4,mats.white);box(x+side*13.5,5.48,z,2,.06,.25,mats.warm);box(x+side*13.7,.45,z+5,.25,.9,.25,mats.trim);}}
 // Raised harbor gantries, an exchange arcade and reservoir rings give districts distinct silhouettes.
 for(const x of [-174,-126]){box(x,5,218,2,10,2,mats.trim,true);box(x,8,245,2,16,2,mats.trim,true);}box(-150,10,218,50,1.2,3,mats.metal);box(-150,16,245,50,1.2,3,mats.metal);box(-184,1.1,250,18,2.2,38,mats.glass,true);
 for(const x of [128,172])box(x,4,194,1,8,38,mats.trim,true);box(150,8,194,45,.6,38,mats.metal);for(let z=180;z<213;z+=8)box(150,7.7,z,42,.12,.12,mats.pink);
 for(const r of [18,25]){const ring=new T.Mesh(new T.TorusGeometry(r,.35,6,64),mats.cyan);ring.rotation.x=Math.PI/2;ring.position.set(0,9,375);root.add(ring);}for(const x of [-26,26])box(x,4.5,375,1,9,1,mats.trim,true);
 sign('Glass Harbor',-150,191,'#9edacb');sign('Neon Exchange',150,150,'#f1a9cd');sign('Memory Depot',150,289,'#d9eaa2');sign('The Reservoir',0,355,'#a8c6ff');sign('Free City / Southbound',0,88,'#ebefa3');
 const coords=[['courier',150,184,'ROOK / MEMORY RUN'],['delivery',150,316,'JUNO / MEMORY DROP'],['blackout',-150,215,'HARBOR / GRID FAILURE'],['echo',0,382,'ECHO / MISSING INSTANCE']];for(const [id,x,z,name]of coords){const g=world.assets['utility-box'].clone();g.position.set(x,0,z);g.scale.setScalar(1.4);scene.add(g);const ring=new T.Mesh(new T.RingGeometry(1,1.15,24),new T.MeshBasicMaterial({color:0xe5ed92,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.05,z);scene.add(ring);pois.push({id,g,ring,position:new T.Vector3(x,1.2,z),name,kind:'roam'});}
 for(const [i,x,z]of [[0,-145,247],[1,157,345],[2,20,403]]){const g=world.prop(i===1?'recon-drone':'warden-drone',x,4.5,z,0,1.15);world.drones.push({g,stun:0,hp:3,home:g.position.clone(),phase:i*1.7,fire:1.7});}
 const shelterLight=new T.MeshBasicMaterial({color:0x1c3c46});for(const x of [-171,-129]){const m=new T.Mesh(new T.BoxGeometry(.5,6,.5),shelterLight);m.position.set(x,3,218);scene.add(m);powerLamps.push(m);}
 const instance=new T.Mesh(new T.IcosahedronGeometry(.6,2),new T.MeshBasicMaterial({color:0xa8c6ff,wireframe:true}));instance.position.set(0,2.4,382);scene.add(instance);
 // Merge per 70 m cell and material so new blocks can be culled independently.
 root.updateMatrixWorld(true);const batches=new Map();root.traverse(m=>{if(!m.isMesh)return;const geo=m.geometry.clone().applyMatrix4(m.matrixWorld);geo.computeBoundingSphere();const p=geo.boundingSphere.center,key=m.material.uuid+':'+Math.floor(p.x/70)+':'+Math.floor(p.z/70);if(!batches.has(key))batches.set(key,{material:m.material,gs:[]});batches.get(key).gs.push(geo);});scene.remove(root);for(const b of batches.values()){const geometry=mergeGeometries(b.gs),mesh=new T.Mesh(geometry,b.material);geometry.computeBoundingSphere();mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);chunks.push(mesh);b.gs.forEach(g=>g.dispose());}
 function populate(cast){for(let i=0;i<10;i++){const g=cast.actors[i%2].g.clone(true);for(const node of [...g.children])if(node.isSprite||node.geometry?.type==='RingGeometry')g.remove(node);const x=[-165,-135,-15,15,135,165][i%6],z=125+(i%4)*65;g.position.set(x,0,z);g.traverse(m=>{if(m.isMesh){m.material=m.material.clone();m.userData.highMaterial=m.material;}});scene.add(g);crowd.push({g,x,z,phase:i*1.8,arms:['L','R'].map(s=>g.getObjectByName('Arm_'+s)),legs:['L','R'].map(s=>g.getObjectByName('Leg_'+s))});}}
 function update(t,dt,player,active,roam){shelterLight.color.set(roam?.jobs.blackout==='complete'?0xffd48d:0x1c3c46);instance.rotation.y=t*.6;instance.position.y=roam?.choices.echo==='free'?11:2.4+Math.sin(t)*.15;instance.visible=instance.position.distanceTo(player)<100;for(const m of chunks){const b=m.geometry?.boundingSphere;if(b&&b.radius>90){m.visible=true;continue;}const p=b?.center||m.position;m.visible=Math.hypot(p.x-player.x,p.z-player.z)<175+(b?.radius||0);}for(const n of crowd){n.g.visible=n.g.position.distanceTo(player)<75;if(!active)continue;const z=n.z+Math.sin(t*.12+n.phase)*15,forward=Math.cos(t*.12+n.phase)>0;n.g.position.z=z;n.g.rotation.y=forward?0:Math.PI;for(let i=0;i<2;i++){if(n.arms[i])n.arms[i].rotation.x=Math.sin(t*7+n.phase)*.3*(i?1:-1);if(n.legs[i])n.legs[i].rotation.x=Math.sin(t*7+n.phase)*.3*(i?-1:1);}}for(const p of pois){const job=p.id==='delivery'?'courier':p.id;p.ring.material.color.set(roam?.jobs[job]==='complete'?0x8df3bd:0xe5ed92);p.ring.visible=p.position.distanceTo(player)<70;p.g.visible=p.position.distanceTo(player)<120;}}
 return {pois,populate,update,destinations:DESTINATIONS,nearest:p=>pois.find(x=>x.position.distanceTo(p)<3.8),crowd};
}
