import * as T from 'three';
import {inWorld} from './shared/roaming.js';
export function advanceVehicle(state,input,dt,clear){let speed=state.speed,heading=state.heading;const throttle=Math.max(-1,Math.min(1,input.throttle||0));speed+=throttle*(Math.sign(throttle)!==Math.sign(speed)&&Math.abs(speed)>1?18:10)*dt;if(!throttle)speed*=Math.exp(-.6*dt);if(input.brake)speed*=Math.exp(-6*dt);speed=Math.max(-9,Math.min(27,speed));if(Math.abs(speed)<.035)speed=0;heading-=(input.steer||0)*Math.min(1,Math.abs(speed)/7)*Math.sign(speed)*dt*.85;const distance=speed*dt,steps=Math.max(1,Math.ceil(Math.abs(distance)/.25));let x=state.x,z=state.z,hit=false;for(let i=0;i<steps;i++){const nx=x+Math.sin(heading)*distance/steps,nz=z+Math.cos(heading)*distance/steps;if(!clear(nx,nz,heading)){speed=0;hit=true;break;}x=nx;z=nz;}return {x,z,heading,speed,hit};}
export function buildVehicles(scene,world,{player,onMessage,onSave,onCollision}){const cars=[];for(const [i,x,z,yaw]of [[0,0,62,0],[1,-145,175,0],[2,145,330,Math.PI]]){const g=world.assets['sentinel-sedan'].clone();g.position.set(x,0,z);g.rotation.y=yaw;scene.add(g);cars.push({id:i,g,heading:yaw,speed:0,home:[x,z,yaw]});}let active=null,lastHit=-100,entryPosition=null;const orbit={x:0,y:.3};
 function pointClear(x,z,r=.5){return inWorld(x,z)&&!world.obstacles.some(o=>!o.disabled&&(o.maxY===undefined||o.maxY>.4)&&Math.abs(x-o.x)<o.w+r&&Math.abs(z-o.z)<o.d+r);}
 function carClear(x,z,heading){for(const dz of [-1.8,0,1.8])if(!pointClear(x+Math.sin(heading)*dz,z+Math.cos(heading)*dz,1.25))return false;return !cars.some(c=>c!==active&&Math.hypot(c.g.position.x-x,c.g.position.z-z)<3.5)&&!world.traffic.some(c=>Math.hypot(c.g.position.x-x,c.g.position.z-z)<3.4);}
 const nearest=()=>cars.filter(c=>c.g.position.distanceTo(player())<5).sort((a,b)=>a.g.position.distanceTo(player())-b.g.position.distanceTo(player()))[0];
 function enter(){const c=nearest();if(!c)return false;entryPosition=player().clone();active=c;c.speed=0;orbit.x=0;orbit.y=.3;onMessage('SENTINEL ONLINE · W/S accelerate / reverse · A/D steer · SPACE brake · E exit when stopped');onSave();return true;}
 function exit(){if(!active)return null;if(Math.abs(active.speed)>1.5){onMessage('Brake before leaving the car.');return null;}const c=active;for(const [side,back]of [[1,0],[-1,0],[0,-1]]){const x=c.g.position.x+Math.cos(c.heading)*side*3-Math.sin(c.heading)*back*4,z=c.g.position.z-Math.sin(c.heading)*side*3-Math.cos(c.heading)*back*4;if(pointClear(x,z)){active=null;c.speed=0;player().set(x,1.85,z);onSave();return c.heading+Math.PI;}}onMessage('The doors are blocked. Move to an open area.');return null;}
 function update(dt,input,camera,t){if(!active)return;const c=active,next=advanceVehicle({x:c.g.position.x,z:c.g.position.z,heading:c.heading,speed:c.speed},input,dt,carClear);c.g.position.set(next.x,0,next.z);c.heading=next.heading;c.speed=next.speed;c.g.rotation.y=c.heading;player().set(next.x,1.85,next.z);if(next.hit&&t-lastHit>1.5){lastHit=t;onCollision();}const a=c.heading+orbit.x,desired=new T.Vector3(next.x-Math.sin(a)*9,3+orbit.y*4,next.z-Math.cos(a)*9);if(!pointClear(desired.x,desired.z,.1)){desired.x=next.x-Math.sin(a)*3;desired.z=next.z-Math.cos(a)*3;}camera.position.lerp(desired,Math.min(1,dt*8));camera.lookAt(next.x+Math.sin(c.heading)*3,1.1,next.z+Math.cos(c.heading)*3);}
 function restore(s){if(s&&pointClear(s.x,s.z,1.2)){cars[0].g.position.set(s.x,0,s.z);cars[0].heading=s.yaw;cars[0].g.rotation.y=s.yaw;}}
 return {blocks:(x,z)=>cars.some(c=>Math.abs((x-c.g.position.x)*Math.cos(c.heading)-(z-c.g.position.z)*Math.sin(c.heading))<1.2&&Math.abs((x-c.g.position.x)*Math.sin(c.heading)+(z-c.g.position.z)*Math.cos(c.heading))<2.5),yieldTraffic:()=>{for(const traffic of world.traffic)traffic.vehicleStop=cars.some(c=>Math.abs(c.g.position.x-traffic.g.position.x)<3.5&&(c.g.position.z-traffic.g.position.z)*Math.sign(traffic.speed)>-2&&(c.g.position.z-traffic.g.position.z)*Math.sign(traffic.speed)<9);},checkpointPosition:()=>{if(!active)return player().toArray();for(const sign of [-1,1]){const x=active.g.position.x+Math.cos(active.heading)*sign*3,z=active.g.position.z-Math.sin(active.heading)*sign*3;if(pointClear(x,z))return [x,1.85,z];}return entryPosition.toArray();},cars,orbit,nearest,enter,exit,update,restore,get active(){return active;},getState:()=>({driving:!!active,speed:Math.round(Math.abs(active?.speed||0)*3.6),cars:cars.map(c=>({id:c.id,position:c.g.position.toArray(),heading:c.heading})),saved:{x:cars[0].g.position.x,z:cars[0].g.position.z,yaw:cars[0].heading}})};
}
