#include "EchelonGame.h"
#include "Camera/CameraComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/BoxComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/InputComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "GameFramework/PlayerController.h"
#include "Engine/Canvas.h"
#include "Engine/StaticMesh.h"
#include "Engine/World.h"
#include "Engine/Engine.h"
#include "Kismet/GameplayStatics.h"
#include "UObject/ConstructorHelpers.h"
#include "PixelStreamingInputComponent.h"
#include "HttpModule.h"
#include "Interfaces/IHttpRequest.h"
#include "Interfaces/IHttpResponse.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonReader.h"
#include "Dom/JsonObject.h"

namespace {
 const FString Backend=TEXT("https://echelon-breakpoint-50221095849.us-central1.run.app");
 AEchelonGameMode* Mode(const AActor* A) { return A&&A->GetWorld()?Cast<AEchelonGameMode>(A->GetWorld()->GetAuthGameMode()):nullptr; }
 FString Encode(const TSharedPtr<FJsonObject>& O) { FString S; auto W=TJsonWriterFactory<>::Create(&S); FJsonSerializer::Serialize(O.ToSharedRef(),W); return S; }
 void TogglePause(APawn* P) { if(auto* PC=Cast<APlayerController>(P->GetController())) { const bool Paused=!PC->IsPaused(); PC->SetPause(Paused); PC->bShowMouseCursor=Paused; if(Paused) PC->SetInputMode(FInputModeGameAndUI()); else PC->SetInputMode(FInputModeGameOnly()); } }
}

AEchelonController::AEchelonController(){BrowserInput=CreateDefaultSubobject<UPixelStreamingInput>(TEXT("BrowserInput"));bEnableClickEvents=true;bEnableTouchEvents=true;}
void AEchelonController::BeginPlay(){Super::BeginPlay();BrowserInput->OnInputEvent.AddDynamic(this,&AEchelonController::ForwardBrowserMessage);}
void AEchelonController::ForwardBrowserMessage(const FString& Descriptor){if(auto* G=Mode(this))G->OnBrowserMessage(Descriptor);}

AEchelonWalker::AEchelonWalker() {
 PrimaryActorTick.bCanEverTick=true;
 Body=CreateDefaultSubobject<UCapsuleComponent>(TEXT("Collision")); SetRootComponent(Body);
 Body->InitCapsuleSize(38,96); Body->SetCollisionProfileName(TEXT("Pawn"));
 Camera=CreateDefaultSubobject<UCameraComponent>(TEXT("Eyes")); Camera->SetupAttachment(Body);
 Camera->SetRelativeLocation(FVector(0,0,89)); Camera->bUsePawnControlRotation=true; Camera->FieldOfView=75;
}
void AEchelonWalker::Forward(float V){ForwardAxis=V;}
void AEchelonWalker::Right(float V){RightAxis=V;}
void AEchelonWalker::Turn(float V){AddControllerYawInput(V*.65f);}
void AEchelonWalker::Look(float V){AddControllerPitchInput(V*.65f);}
void AEchelonWalker::Interact(){if(auto* G=Mode(this))G->Interact();}
void AEchelonWalker::Pause(){TogglePause(this);}
void AEchelonWalker::SetupPlayerInputComponent(UInputComponent* I){Super::SetupPlayerInputComponent(I);I->BindAxis("Forward",this,&AEchelonWalker::Forward);I->BindAxis("Right",this,&AEchelonWalker::Right);I->BindAxis("Turn",this,&AEchelonWalker::Turn);I->BindAxis("Look",this,&AEchelonWalker::Look);I->BindAction("Interact",IE_Pressed,this,&AEchelonWalker::Interact);I->BindAction("Pause",IE_Pressed,this,&AEchelonWalker::Pause).bExecuteWhenPaused=true;}
void AEchelonWalker::Tick(float Dt){Super::Tick(Dt);if(!IsPlayerControlled())return;const auto* G=Mode(this);const bool External=G&&G->ExternalUntil>GetWorld()->GetTimeSeconds();const float F=External?G->ExternalForward:ForwardAxis,S=External?G->ExternalRight:RightAxis;const FRotator R(0,GetControlRotation().Yaw,0);FVector V=R.Vector()*F+FRotationMatrix(R).GetUnitAxis(EAxis::Y)*S;V=V.GetClampedToMaxSize(1)*550*FMath::Min(Dt,.1f);if(AEchelonGameMode::InsideCity(GetActorLocation()+V))AddActorWorldOffset(V,true);}

AEchelonCar::AEchelonCar(){PrimaryActorTick.bCanEverTick=true;Body=CreateDefaultSubobject<UBoxComponent>(TEXT("Chassis"));SetRootComponent(Body);Body->SetBoxExtent(FVector(220,95,80));Body->SetCollisionProfileName(TEXT("Pawn"));Mesh=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Sentinel"));Mesh->SetupAttachment(Body);Mesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);Mesh->SetRelativeLocation(FVector(0,0,-80));static ConstructorHelpers::FObjectFinder<UStaticMesh> CarAsset(TEXT("/Game/Echelon/sentinel_sedan.sentinel_sedan"));if(CarAsset.Succeeded())Mesh->SetStaticMesh(CarAsset.Object);Arm=CreateDefaultSubobject<USpringArmComponent>(TEXT("ChaseArm"));Arm->SetupAttachment(Body);Arm->TargetArmLength=750;Arm->SetRelativeLocation(FVector(0,0,160));Arm->SetRelativeRotation(FRotator(-15,0,0));Arm->bEnableCameraLag=true;Arm->CameraLagSpeed=7;Camera=CreateDefaultSubobject<UCameraComponent>(TEXT("ChaseCamera"));Camera->SetupAttachment(Arm);Camera->FieldOfView=78;}
void AEchelonCar::Forward(float V){Throttle=V;}
void AEchelonCar::Right(float V){Steer=V;}
void AEchelonCar::BrakeDown(){Braking=true;}
void AEchelonCar::BrakeUp(){Braking=false;}
void AEchelonCar::Interact(){if(auto* G=Mode(this))G->Interact();}
void AEchelonCar::Pause(){TogglePause(this);}
void AEchelonCar::SetupPlayerInputComponent(UInputComponent* I){Super::SetupPlayerInputComponent(I);I->BindAxis("Forward",this,&AEchelonCar::Forward);I->BindAxis("Right",this,&AEchelonCar::Right);I->BindAction("Interact",IE_Pressed,this,&AEchelonCar::Interact);I->BindAction("Brake",IE_Pressed,this,&AEchelonCar::BrakeDown);I->BindAction("Brake",IE_Released,this,&AEchelonCar::BrakeUp);I->BindAction("Pause",IE_Pressed,this,&AEchelonCar::Pause).bExecuteWhenPaused=true;}
void AEchelonCar::Tick(float Dt){Super::Tick(Dt);if(!IsPlayerControlled()){Speed=0;return;}Dt=FMath::Min(Dt,.1f);const auto* G=Mode(this);if(G&&G->ExternalUntil>GetWorld()->GetTimeSeconds()){Throttle=G->ExternalForward;Steer=G->ExternalRight;Braking=G->ExternalBrake;}Speed+=Throttle*900*Dt;if(FMath::IsNearlyZero(Throttle))Speed*=FMath::Exp(-.6f*Dt);if(Braking)Speed*=FMath::Exp(-7*Dt);Speed=FMath::Clamp(Speed,-800.f,2500.f);AddActorWorldRotation(FRotator(0,Steer*FMath::Min(1.f,FMath::Abs(Speed)/650)*FMath::Sign(Speed)*Dt*48,0),true);const FVector Delta=GetActorForwardVector()*Speed*Dt;if(!AEchelonGameMode::InsideCity(GetActorLocation()+Delta)){Speed=0;return;}FHitResult Hit;AddActorWorldOffset(Delta,true,&Hit);if(Hit.IsValidBlockingHit())Speed=0;}

AEchelonMara::AEchelonMara(){PrimaryActorTick.bCanEverTick=true;Body=CreateDefaultSubobject<UCapsuleComponent>(TEXT("Collision"));SetRootComponent(Body);Body->InitCapsuleSize(35,95);Body->SetCollisionProfileName(TEXT("Pawn"));Mesh=CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mara"));Mesh->SetupAttachment(Body);Mesh->SetRelativeLocation(FVector(0,0,-95));Mesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);static ConstructorHelpers::FObjectFinder<UStaticMesh> Asset(TEXT("/Game/Echelon/npc_mara.npc_mara"));if(Asset.Succeeded())Mesh->SetStaticMesh(Asset.Object);}
void AEchelonMara::BeginPlay(){Super::BeginPlay();Home=GetActorLocation();}
void AEchelonMara::Tick(float Dt){Super::Tick(Dt);Time+=Dt;const auto* P=UGameplayStatics::GetPlayerPawn(this,0);FVector Target=Following&&P?P->GetActorLocation():Home+FVector(FMath::Sin(Time*.13f)*250,FMath::Cos(Time*.11f)*180,0);FVector V=Target-GetActorLocation();V.Z=0;if(V.Size()<(Following?350:35))return;V=V.GetSafeNormal()*FMath::Min(Dt,.1f)*110;FHitResult Hit;if(AEchelonGameMode::InsideCity(GetActorLocation()+V))AddActorWorldOffset(V,true,&Hit);if(Hit.IsValidBlockingHit()){const FVector Side=FVector(-V.Y,V.X,0);if(AEchelonGameMode::InsideCity(GetActorLocation()+Side))AddActorWorldOffset(Side,true);}SetActorRotation(V.Rotation());}

AEchelonGameMode::AEchelonGameMode(){DefaultPawnClass=AEchelonWalker::StaticClass();PlayerControllerClass=AEchelonController::StaticClass();HUDClass=AEchelonHUD::StaticClass();PrimaryActorTick.bCanEverTick=true;}
bool AEchelonGameMode::InsideCity(const FVector& P){const float X=P.Y/100,Z=P.X/100;return FMath::IsFinite(X)&&FMath::IsFinite(Z)&&X>-235&&X<235&&Z>-136&&Z<425&&(Z>=75||FMath::Abs(X)<68);}
void AEchelonGameMode::StartPlay(){Super::StartPlay();Session=FGuid::NewGuid().ToString(EGuidFormats::Digits).ToLower()+FGuid::NewGuid().ToString(EGuidFormats::Digits).ToLower();Walker=Cast<AEchelonWalker>(UGameplayStatics::GetPlayerPawn(this,0));FActorSpawnParameters Params;Params.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;Car=GetWorld()->SpawnActor<AEchelonCar>(FVector(6200,0,80),FRotator::ZeroRotator,Params);Mara=GetWorld()->SpawnActor<AEchelonMara>(FVector(4900,-800,95),FRotator::ZeroRotator,Params);if(auto* PC=UGameplayStatics::GetPlayerController(this,0))StreamInput=PC->FindComponentByClass<UPixelStreamingInput>();}
void AEchelonGameMode::Tick(float Dt){Super::Tick(Dt);NextThink-=Dt;NextSave-=Dt;if(NextThink<=0){NextThink=75;AskMara(TEXT(""));}if(NextSave<=0){NextSave=25;SaveCheckpoint();}}
void AEchelonGameMode::Interact(){auto* PC=UGameplayStatics::GetPlayerController(this,0);if(!PC||!Car||!Walker)return;if(PC->GetPawn()==Car){if(FMath::Abs(Car->Speed)>150){Speech=TEXT("Brake before leaving the Sentinel.");return;}FVector Exit=Car->GetActorLocation()+Car->GetActorRightVector()*320;Exit.Z=96;FCollisionQueryParams Query;Query.AddIgnoredActor(Car);Query.AddIgnoredActor(Walker);if(!InsideCity(Exit)||GetWorld()->OverlapBlockingTestByChannel(Exit,FQuat::Identity,ECC_Pawn,FCollisionShape::MakeCapsule(38,96),Query)){Speech=TEXT("The door is blocked. Move the car into open space.");return;}Walker->SetActorLocation(Exit);Walker->SetActorHiddenInGame(false);Walker->SetActorEnableCollision(true);PC->Possess(Walker);SaveCheckpoint();return;}if(FVector::Dist(Walker->GetActorLocation(),Car->GetActorLocation())<500){PC->Possess(Car);Walker->SetActorHiddenInGame(true);Walker->SetActorEnableCollision(false);Speech=TEXT("SENTINEL / W-S drive, A-D steer, Space brake, E exit.");}else if(Mara&&FVector::Dist(Walker->GetActorLocation(),Mara->GetActorLocation())<550)AskMara(TEXT("What happened to Iona, and what aren't you telling me?"));else Speech=TEXT("Approach a Sentinel or Mara to interact.");}
void AEchelonGameMode::SendBrowser(const FString& Kind,const FString& Text){auto J=MakeShared<FJsonObject>();J->SetStringField(TEXT("kind"),Kind);J->SetStringField(TEXT("text"),Text);if(StreamInput)StreamInput->SendPixelStreamingResponse(Encode(J));}
void AEchelonGameMode::OnBrowserMessage(const FString& Descriptor){TSharedPtr<FJsonObject> J;if(!FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Descriptor),J)||!J.IsValid())return;FString Type;if(!J->TryGetStringField(TEXT("type"),Type))return;if(Type==TEXT("echelon.talk")){FString Q;if(J->TryGetStringField(TEXT("message"),Q))AskMara(Q.Left(400));}else if(Type==TEXT("echelon.interact"))Interact();else if(Type==TEXT("echelon.input")){double F=0,R=0;bool B=false;if(J->TryGetNumberField(TEXT("forward"),F)&&J->TryGetNumberField(TEXT("right"),R)&&FMath::IsFinite(F)&&FMath::IsFinite(R)){J->TryGetBoolField(TEXT("brake"),B);ExternalForward=FMath::Clamp(static_cast<float>(F),-1.f,1.f);ExternalRight=FMath::Clamp(static_cast<float>(R),-1.f,1.f);ExternalBrake=B;ExternalUntil=GetWorld()->GetTimeSeconds()+.3f;}}else if(Type==TEXT("echelon.look")){double X=0,Y=0;if(J->TryGetNumberField(TEXT("dx"),X)&&J->TryGetNumberField(TEXT("dy"),Y)&&FMath::IsFinite(X)&&FMath::IsFinite(Y))if(auto* PC=UGameplayStatics::GetPlayerController(this,0)){FRotator Rotation=PC->GetControlRotation();Rotation.Yaw+=FMath::Clamp(X,-100.,100.)*.16;Rotation.Pitch=FMath::Clamp(FRotator::NormalizeAxis(Rotation.Pitch)-FMath::Clamp(Y,-100.,100.)*.16,-75.,75.);PC->SetControlRotation(Rotation);}}}
void AEchelonGameMode::AskMara(const FString& Question){if(Busy||!Mara)return;Busy=true;Connection=TEXT("CONTACTING MARA");auto Root=MakeShared<FJsonObject>(),Snapshot=MakeShared<FJsonObject>(),Cast=MakeShared<FJsonObject>(),MaraState=MakeShared<FJsonObject>();TArray<TSharedPtr<FJsonValue>> Memories;for(const auto& M:Memory)Memories.Add(MakeShared<FJsonValueString>(M));MaraState->SetArrayField(TEXT("memory"),Memories);MaraState->SetBoolField(TEXT("met"),true);Cast->SetObjectField(TEXT("mara"),MaraState);Snapshot->SetObjectField(TEXT("cast"),Cast);Snapshot->SetBoolField(TEXT("signal"),false);Snapshot->SetNumberField(TEXT("health"),100);Root->SetObjectField(TEXT("snapshot"),Snapshot);if(!Question.IsEmpty()){auto Interaction=MakeShared<FJsonObject>();Interaction->SetStringField(TEXT("id"),TEXT("mara"));Interaction->SetStringField(TEXT("message"),Question.Left(400));Root->SetObjectField(TEXT("interaction"),Interaction);}auto Request=FHttpModule::Get().CreateRequest();Request->SetURL(Backend+TEXT("/api/cast"));Request->SetVerb(TEXT("POST"));Request->SetHeader(TEXT("Content-Type"),TEXT("application/json"));Request->SetHeader(TEXT("Authorization"),TEXT("Bearer ")+Session);Request->SetContentAsString(Encode(Root));Request->SetTimeout(15);TWeakObjectPtr<AEchelonGameMode> Weak(this);Request->OnProcessRequestComplete().BindLambda([Weak](FHttpRequestPtr,FHttpResponsePtr Response,bool Ok){if(!Weak.IsValid())return;auto* G=Weak.Get();G->Busy=false;G->Connection=TEXT("LOCAL FALLBACK");TSharedPtr<FJsonObject> J;if(Ok&&Response.IsValid()&&Response->GetResponseCode()==200&&FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Response->GetContentAsString()),J)){const TArray<TSharedPtr<FJsonValue>>* Characters=nullptr;FString Source;J->TryGetStringField(TEXT("source"),Source);if(J->TryGetArrayField(TEXT("characters"),Characters))for(const auto& V:*Characters){const auto N=V->AsObject();if(!N.IsValid())continue;FString Id,Line,Goal;N->TryGetStringField(TEXT("id"),Id);if(Id!=TEXT("mara")||!N->TryGetStringField(TEXT("line"),Line))continue;G->Speech=TEXT("Mara: ")+Line.Left(220);G->Memory.Add(Line.Left(220));while(G->Memory.Num()>6)G->Memory.RemoveAt(0);N->TryGetStringField(TEXT("goal"),Goal);if(G->Mara)G->Mara->Following=Goal==TEXT("follow")||Goal==TEXT("assist");G->Connection=Source==TEXT("gemini")?TEXT("GEMINI / MARA"):TEXT("LOCAL / MARA");G->SendBrowser(TEXT("dialogue"),G->Speech);G->SaveCheckpoint();return;}}G->Speech=TEXT("Mara: If the network goes quiet, trust what you can verify. I signed the first override. Iona refused it.");G->SendBrowser(TEXT("dialogue"),G->Speech);});if(!Request->ProcessRequest()){Busy=false;Connection=TEXT("LOCAL FALLBACK");}}
void AEchelonGameMode::SaveCheckpoint(){const auto* P=UGameplayStatics::GetPlayerPawn(this,0);if(!P||!InsideCity(P->GetActorLocation()))return;const FVector Position=P->GetActorLocation();auto Root=MakeShared<FJsonObject>(),Save=MakeShared<FJsonObject>(),Campaign=MakeShared<FJsonObject>(),Story=MakeShared<FJsonObject>(),Cast=MakeShared<FJsonObject>(),N=MakeShared<FJsonObject>();TArray<TSharedPtr<FJsonValue>> MemoryValues;for(const auto& M:Memory)MemoryValues.Add(MakeShared<FJsonValueString>(M));N->SetArrayField(TEXT("memory"),MemoryValues);N->SetBoolField(TEXT("met"),Memory.Num()>0);Cast->SetObjectField(TEXT("mara"),N);Story->SetObjectField(TEXT("cast"),Cast);Campaign->SetObjectField(TEXT("story"),Story);Save->SetObjectField(TEXT("campaign"),Campaign);Save->SetArrayField(TEXT("position"),{MakeShared<FJsonValueNumber>(Position.Y/100),MakeShared<FJsonValueNumber>(1.85),MakeShared<FJsonValueNumber>(Position.X/100)});Save->SetNumberField(TEXT("health"),100);Root->SetObjectField(TEXT("save"),Save);auto Request=FHttpModule::Get().CreateRequest();Request->SetURL(Backend+TEXT("/api/save"));Request->SetVerb(TEXT("PUT"));Request->SetHeader(TEXT("Content-Type"),TEXT("application/json"));Request->SetHeader(TEXT("Authorization"),TEXT("Bearer ")+Session);Request->SetContentAsString(Encode(Root));Request->SetTimeout(10);Request->ProcessRequest();}
void AEchelonHUD::DrawHUD(){Super::DrawHUD();if(!Canvas)return;auto* G=Mode(this);if(!G)return;DrawText(TEXT("ECHELON / UNREAL PREVIEW"),FColor(200,245,235),30,25,nullptr,1.3f);DrawText(TEXT("WASD move / drive   Mouse look   E interact   Space brake   Esc release cursor"),FColor::White,30,Canvas->SizeY-35);DrawText(G->Connection,FColor(230,237,151),30,60);DrawRect(FLinearColor(0.02f,.06f,.08f,.8f),25,Canvas->SizeY-145,Canvas->SizeX-50,85);DrawText(G->Speech.Left(110),FColor::White,40,Canvas->SizeY-125);if(G->Speech.Len()>110)DrawText(G->Speech.Mid(110,110),FColor::White,40,Canvas->SizeY-100);DrawRect(FLinearColor(.1f,.2f,.23f,.8f),Canvas->SizeX-155,100,125,55);DrawText(TEXT("INTERACT"),FColor::White,Canvas->SizeX-145,117);AddHitBox(FVector2D(Canvas->SizeX-155,100),FVector2D(125,55),TEXT("Interact"),true);if(G->Car&&GetOwningPawn()==G->Car)DrawText(FString::Printf(TEXT("%d KM/H"),FMath::RoundToInt(FMath::Abs(G->Car->Speed)*.036f)),FColor(230,237,151),Canvas->SizeX*.45f,Canvas->SizeY-195,nullptr,1.6f);}
void AEchelonHUD::NotifyHitBoxClick(FName Name){Super::NotifyHitBoxClick(Name);if(Name==TEXT("Interact"))if(auto* G=Mode(this))G->Interact();}
