import {test,expect} from '@playwright/test';
const state=p=>p.evaluate(()=>window.echelon.getState());
async function open(page,position,campaign={}){await page.addInitScript(({position,campaign})=>localStorage.setItem('echelon-v2-save',JSON.stringify({position,relays:[false,false,false],health:100,kills:0,campaign:{version:1,...campaign}})),{position,campaign});await page.goto('/?quality=balanced');await page.waitForFunction(()=>window.echelon?.getState().ready,null,{timeout:90000});await page.locator('#continue').click();}
test('transit signal begins the authored mission and survives reload',async({page})=>{await open(page,[49,1.85,10]);await page.keyboard.press('e');await expect.poll(async()=>(await state(page)).campaign.signal).toBe(true);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('echelon-v2-save')).campaign.signal)).toBe(true);await page.keyboard.press('Escape');await page.reload();await page.waitForFunction(()=>window.echelon?.getState().ready);await page.locator('#continue').click();expect((await state(page)).campaign.signal).toBe(true);});
test('rescuing Imani changes the story and saves the choice',async({page})=>{await open(page,[-49,1.85,40],{signal:true});await page.keyboard.press('e');await expect(page.locator('#story-dialog')).toBeVisible();await page.screenshot({path:'living-city-choice.png'});await page.getByRole('button',{name:/RESCUE IMANI/}).click();await expect.poll(async()=>(await state(page)).campaign.choice).toBe('rescue');expect((await state(page)).campaign.salvage).toBe(2);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('echelon-v2-save')).campaign.choice)).toBe('rescue');});
test('taking the capacitor grants weapon upgrade and triggers lockdown',async({page})=>{await open(page,[-49,1.85,40],{signal:true});await page.keyboard.press('e');await page.getByRole('button',{name:/TAKE CAPACITOR/}).click();await expect.poll(async()=>(await state(page)).campaign.choice).toBe('steal');expect((await state(page)).campaign.upgrades).toContain('capacitor');await expect.poll(async()=>(await state(page)).gates[0].closed).toBe(true);});
test('workbench purchases and rooftop recordings persist',async({page})=>{await open(page,[-49,1.85,35],{signal:true,salvage:3});await page.keyboard.press('e');await page.getByRole('button',{name:/QUIET RUNNER/}).click();expect((await state(page)).campaign.upgrades).toContain('stealth');expect((await state(page)).campaign.salvage).toBe(1);
});
test('rooftop recording can be collected from a restored roof checkpoint',async({page})=>{await open(page,[-49,7.85,-5],{signal:true});await expect.poll(async()=>(await state(page)).position[1]).toBeGreaterThan(7);await page.keyboard.press('e');await expect.poll(async()=>(await state(page)).campaign.recordings).toContain('roof-record');await page.screenshot({path:'living-city-rooftop.png'});});
test('mission rooms and service ramp are reachable in collision map',async({page})=>{await open(page,[1.8,1.85,61]);const nav=await page.evaluate(()=>window.echelon.getNavigation());const obstacles=nav.obstacles;const floor=(x,z)=>x>=-57&&x<=-41&&z>=-10&&z<=10?6:x>=-51&&x<=-47&&z>10&&z<=30?(30-z)*.3:0;
 const targets=[[49,10],[-49,40],[-49,-5]],queue=[[2,61]],seen=new Set(['2,61']);let head=0;while(head<queue.length){const [x,z]=queue[head++],y=floor(x,z);for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,nz=z+dz,k=nx+','+nz,ny=floor(nx,nz);if(nx<=-68||nx>=68||nz<=-136||nz>=74||seen.has(k)||ny-y>.65)continue;if(obstacles.some(o=>!o.disabled&&(o.maxY===undefined||ny<o.maxY-.05)&&Math.abs(nx-o.x)<o.w&&Math.abs(nz-o.z)<o.d))continue;seen.add(k);queue.push([nx,nz]);}}
 for(const [x,z]of targets)expect(seen.has(x+','+z),`reachable ${x},${z}`).toBe(true);
});
