import {inWorld} from '../shared/roaming.js';
import {directCast,cleanInteraction} from './cast.mjs';
import {castSnapshot,available} from '../shared/cast.js';
import http from 'node:http';import {gzipSync} from 'node:zlib';import {readFile,stat} from 'node:fs/promises';import path from 'node:path';
import {restoreCampaign} from '../campaign.js';
import {Store,sessionID} from './store.mjs';import {direct} from './director.mjs';import {cleanSnapshot} from '../shared/director.js';
const staticCache=new Map();let cachedBytes=0;let globalRate={minute:0,count:0};
const store=new Store(),root=path.resolve(process.env.STATIC_ROOT||'dist'),limits=new Map(),locks=new Set();
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
async function body(req){let text='';for await(const c of req){text+=c;if(text.length>48000)throw Object.assign(new Error('Request too large'),{status:413});}try{return JSON.parse(text||'{}');}catch{throw Object.assign(new Error('Invalid JSON'),{status:400});}}
function validSave(s){if(!s||!Array.isArray(s.position)||s.position.length!==3||!s.position.every(Number.isFinite)||!inWorld(s.position[0],s.position[2]))return null;return {position:s.position.map(Number),health:Math.max(1,Math.min(100,Number(s.health)||100)),kills:Math.max(0,Math.min(1000,Number(s.kills)||0)),relays:[0,1,2].map(i=>!!s.relays?.[i]),campaign:s.campaign?restoreCampaign(s.campaign):null,updated:Math.min(Date.now()+30000,Math.max(0,Number(s.updated)||Date.now()))};}
async function claimLease(key,patch,guard){for(let i=0;i<3;i++){const row=await store.read(key);if(guard(row?.data||{}))return null;try{await store.write(key,{...row?.data,...patch},row?.version||null);return row?.data||{};}catch(e){if(i===2)throw e;}}}
export const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/health')return json(res,200,{ok:true});if(u.pathname.startsWith('/api/')){const minute=Math.floor(Date.now()/60000);if(globalRate.minute!==minute)globalRate={minute,count:0};if(++globalRate.count>200)return json(res,429,{error:'Service busy'});
 const origin=req.headers.origin;if(origin){let host;try{host=new URL(origin).host;}catch{return json(res,403,{error:'Origin rejected'});}if(host!==req.headers.host)return json(res,403,{error:'Origin rejected'});}
 const token=(req.headers.authorization||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token))return json(res,401,{error:'A session token is required'});const id=sessionID(token),key=`sessions/${id}`,now=Date.now();
 const rate=limits.get(id)||{at:now,count:0};if(now-rate.at>60000){rate.at=now;rate.count=0;}if(++rate.count>20)return json(res,429,{error:'Try again shortly'});limits.set(id,rate);if(limits.size>5000)for(const [k,v]of limits)if(now-v.at>60000)limits.delete(k);
 if(u.pathname==='/api/session'&&req.method==='GET'){const row=await store.read(key);return json(res,200,{save:row?.data?.save||null,plan:row?.data?.plan||null,persistent:store.cloud});}
 if(u.pathname==='/api/save'&&req.method==='PUT'){const b=await body(req),save=validSave(b.save);if(!save)return json(res,400,{error:'Invalid checkpoint'});for(let i=0;i<3;i++){const row=await store.read(key);try{await store.write(key,{...row?.data,save},row?.version||null);return json(res,200,{saved:true,persistent:store.cloud});}catch(e){if(i===2)throw e;}}}
 if(u.pathname==='/api/cast'&&req.method==='POST'){const b=await body(req),snapshot=castSnapshot({story:b.snapshot,signal:b.snapshot?.signal,choice:b.snapshot?.choice},b.snapshot),interaction=cleanInteraction(b.interaction);if(b.interaction&&!interaction)return json(res,400,{error:'Invalid interaction'});if(interaction&&!available(interaction.id,snapshot))return json(res,400,{error:'Character unavailable'});const row=await store.read(key),leaseKey='cast:'+id;if(locks.has(leaseKey))return json(res,429,{error:'Characters are responding'});if(interaction&&row?.data?.lastCastInteraction>now-8000)return json(res,429,{error:'Let the character finish'});if(!interaction&&row?.data?.nextCast>now)return row.data.castPlan?json(res,200,{...row.data.castPlan,cached:true}):json(res,429,{error:'Characters are thinking'});locks.add(leaseKey);try{const claimed=await claimLease(key,{nextCast:now+75000,...interaction?{lastCastInteraction:now}:{}},d=>interaction?d.lastCastInteraction>now-8000:d.nextCast>now);if(!claimed)return json(res,429,{error:'Characters are thinking'});const revision=(claimed.castPlan?.revision||0)+1;const plan=await directCast(snapshot,interaction,revision,store);for(let i=0;i<3;i++){const latest=await store.read(key);try{await store.write(key,{...latest?.data,castPlan:plan},latest?.version||null);break;}catch(e){if(i===2)throw e;}}return json(res,200,plan);}finally{locks.delete(leaseKey);}}
 if(u.pathname==='/api/director'&&req.method==='POST'){const b=await body(req),row=await store.read(key);if(row?.data?.nextDirector>now)return row.data.plan?json(res,200,{...row.data.plan,cached:true}):json(res,429,{error:'Director is thinking'});if(locks.has(id))return json(res,429,{error:'Director is thinking'});locks.add(id);try{
 // Claim a per-session lease using a database precondition before spending on a model.
 const claimed=await claimLease(key,{nextDirector:now+45000},d=>d.nextDirector>now);if(!claimed)return json(res,429,{error:'Director is thinking'});const revision=(claimed.plan?.revision||0)+1;const plan=await direct(cleanSnapshot(b.snapshot),revision,store);plan.context=cleanSnapshot(b.snapshot);
 for(let i=0;i<3;i++){const latest=await store.read(key);try{await store.write(key,{...latest?.data,plan},latest?.version||null);break;}catch(e){if(i===2)throw e;}}return json(res,200,plan);
 }finally{locks.delete(id);}}
 return json(res,404,{error:'Not found'});
 }
 if(!['GET','HEAD'].includes(req.method))return json(res,405,{error:'Method not allowed'});let name=decodeURIComponent(u.pathname);if(name==='/')name='/index.html';const file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep))return json(res,403,{error:'Forbidden'});let info;try{info=await stat(file);}catch{return json(res,404,{error:'Not found'});}if(!info.isFile())return json(res,404,{error:'Not found'});const ext=path.extname(file),types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.glb':'model/gltf-binary','.webp':'image/webp','.mp3':'audio/mpeg','.svg':'image/svg+xml','.hdr':'application/octet-stream'};let data=staticCache.get(file);if(!data||data.mtime!==info.mtimeMs){const raw=await readFile(file);data={raw,mtime:info.mtimeMs,gzip:/\.(html|js|css|json|glb)$/.test(file)?gzipSync(raw):null};if(cachedBytes>50000000){staticCache.clear();cachedBytes=0;}staticCache.set(file,data);cachedBytes+=raw.length+(data.gzip?.length||0);}
 const headers={'Content-Type':types[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes','Vary':'Accept-Encoding'};let bytes=data.raw,status=200;const range=req.headers.range?.match(/^bytes=(\d+)-(\d*)$/);if(range){const start=Number(range[1]),end=range[2]?Math.min(Number(range[2]),bytes.length-1):bytes.length-1;if(start>end||start>=bytes.length){res.writeHead(416,{'Content-Range':`bytes */${bytes.length}`});return res.end();}headers['Content-Range']=`bytes ${start}-${end}/${bytes.length}`;bytes=bytes.subarray(start,end+1);status=206;}else if(data.gzip&&req.headers['accept-encoding']?.includes('gzip')){bytes=data.gzip;headers['Content-Encoding']='gzip';}headers['Content-Length']=bytes.length;res.writeHead(status,headers);res.end(req.method==='HEAD'?undefined:bytes);

 }catch(e){console.error('Request failed:',e.message);if(!res.headersSent)json(res,e.status||503,{error:'Service temporarily unavailable'});else res.end();}});
server.listen(Number(process.env.PORT)||8080,()=>console.log('Echelon world server ready'));
