import {createHash} from 'node:crypto';
let cachedToken,tokenUntil=0;
export async function accessToken(){if(process.env.GOOGLE_ACCESS_TOKEN)return process.env.GOOGLE_ACCESS_TOKEN;if(cachedToken&&Date.now()<tokenUntil)return cachedToken;const r=await fetch('http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token',{headers:{'Metadata-Flavor':'Google'},signal:AbortSignal.timeout(2500)});if(!r.ok)throw new Error('Runtime identity unavailable');const j=await r.json();cachedToken=j.access_token;tokenUntil=Date.now()+(j.expires_in-120)*1000;return cachedToken;}
export const sessionID=token=>createHash('sha256').update(token).digest('hex');
export class Store{
 constructor(){this.memory=new Map();this.cloud=!!process.env.GCP_PROJECT;this.root=`https://firestore.googleapis.com/v1/projects/${process.env.GCP_PROJECT}/databases/${process.env.FIRESTORE_DATABASE||'echelon-world'}/documents`;}
 async read(key){if(!this.cloud)return structuredClone(this.memory.get(key)||null);const r=await fetch(`${this.root}/${key}`,{headers:{Authorization:`Bearer ${await accessToken()}`},signal:AbortSignal.timeout(5000)});if(r.status===404)return null;if(!r.ok)throw new Error(`Persistence read ${r.status}`);const d=await r.json();return {data:JSON.parse(d.fields.payload.stringValue),version:d.updateTime};}
 async write(key,data,version){if(!this.cloud){const prior=this.memory.get(key);if(version===null&&prior||typeof version==='string'&&prior?.version!==version)throw new Error('Conflict');const out={data:structuredClone(data),version:String((Number(prior?.version)||0)+1)};this.memory.set(key,out);return out;}
 const q=version===null?'?currentDocument.exists=false':version?'?currentDocument.updateTime='+encodeURIComponent(version):'';
 const r=await fetch(`${this.root}/${key}${q}`,{method:'PATCH',headers:{Authorization:`Bearer ${await accessToken()}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(data)},updated:{timestampValue:new Date().toISOString()}}}),signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error(`Persistence write ${r.status}`);const d=await r.json();return {data,version:d.updateTime};}
 async budget(){const day=new Date().toISOString().slice(0,10),key=`budgets/${day}`;for(let i=0;i<3;i++){const row=await this.read(key),d=row?.data||{calls:0,minute:0,minuteCalls:0};const minute=Math.floor(Date.now()/60000);if(d.minute!==minute){d.minute=minute;d.minuteCalls=0;}if(d.calls>=Number(process.env.AI_DAILY_LIMIT||300)||d.minuteCalls>=12)return false;d.calls++;d.minuteCalls++;try{await this.write(key,d,row?.version||null);return true;}catch{}}return false;}
}
