import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {randomBytes} from 'node:crypto';
let child;const base='http://127.0.0.1:5192',token=randomBytes(32).toString('hex'),auth={Authorization:'Bearer '+token,'Content-Type':'application/json'};
before(async()=>{child=spawn(process.execPath,['server/main.mjs'],{env:{...process.env,GCP_PROJECT:'',PORT:'5192'},stdio:'ignore'});for(let i=0;i<50;i++){try{if((await fetch(base+'/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw new Error('Server did not start');});after(()=>child?.kill());
test('session checkpoints are isolated, durable within local store, and validated',async()=>{assert.equal((await fetch(base+'/api/session')).status,401);let r=await fetch(base+'/api/save',{method:'PUT',headers:auth,body:JSON.stringify({save:{position:[49,1.85,10],relays:[false,false,false],health:82,campaign:{signal:true,salvage:2}}})});assert.equal(r.status,200);const saved=await(await fetch(base+'/api/session',{headers:auth})).json();assert.equal(saved.save.campaign.signal,true);assert.equal(saved.save.health,82);const other=await(await fetch(base+'/api/session',{headers:{Authorization:'Bearer '+randomBytes(32).toString('hex')}})).json();assert.equal(other.save,null);r=await fetch(base+'/api/save',{method:'PUT',headers:auth,body:JSON.stringify({save:{position:[999,0,0]}})});assert.equal(r.status,400);});
test('director falls back offline and reuses its per-session lease',async()=>{const call=()=>fetch(base+'/api/director',{method:'POST',headers:auth,body:JSON.stringify({snapshot:{health:20,alert:90,district:'market'}})});const first=await(await call()).json(),second=await(await call()).json();assert.equal(first.source,'local');assert.equal(first.revision,second.revision);assert.equal(second.cached,true);assert(first.actions.some(a=>a.type==='route'&&a.value==='open'));});
test('cross-origin writes are rejected and audio supports byte ranges',async()=>{const r=await fetch(base+'/api/save',{method:'PUT',headers:{...auth,Origin:'https://unrelated.example'},body:'{}'});assert.equal(r.status,403);const audio=await fetch(base+'/assets/floating-in-space.mp3',{headers:{Range:'bytes=0-99'}});assert.equal(audio.status,206);assert.equal((await audio.arrayBuffer()).byteLength,100);});
test('character endpoint rejects impossible cast and returns a bounded offline ensemble',async()=>{let r=await fetch(base+'/api/cast',{method:'POST',headers:auth,body:JSON.stringify({snapshot:{choice:'steal'},interaction:{id:'imani',message:'Hello'}})});assert.equal(r.status,400);r=await fetch(base+'/api/cast',{method:'POST',headers:auth,body:JSON.stringify({snapshot:{signal:true,choice:'rescue'}})});assert.equal(r.status,200);const p=await r.json();assert.equal(p.source,'local');assert.equal(p.characters.length,4);assert(p.characters.every(n=>typeof n.line==='string'&&n.line.length<=220));});
test('simultaneous world, cast and save requests preserve all session fields',async()=>{const headers={Authorization:'Bearer '+randomBytes(32).toString('hex'),'Content-Type':'application/json'};const responses=await Promise.all([fetch(base+'/api/cast',{method:'POST',headers,body:JSON.stringify({snapshot:{signal:true}})}),fetch(base+'/api/director',{method:'POST',headers,body:JSON.stringify({snapshot:{signal:true}})}),fetch(base+'/api/save',{method:'PUT',headers,body:JSON.stringify({save:{position:[1.8,1.85,61],health:77,campaign:{signal:true}}})})]);assert(responses.every(r=>r.status===200));const restored=await(await fetch(base+'/api/session',{headers})).json();assert.equal(restored.save.health,77);assert(restored.plan);});

test('expanded district and roaming state round trip through save API',async()=>{const save={position:[150,1.85,310],health:90,campaign:{roam:{jobs:{courier:'complete'},choices:{courier:'private'},waypoint:'archive',vehicle:{x:150,z:300,yaw:0}}}};const r=await fetch(base+'/api/save',{method:'PUT',headers:auth,body:JSON.stringify({save})});assert.equal(r.status,200);const restored=await(await fetch(base+'/api/session',{headers:auth})).json();assert.deepEqual(restored.save.position,save.position);assert.equal(restored.save.campaign.roam.jobs.courier,'complete');});
