import {inWorld} from './roaming.js';
// Authored canon stays fixed; the model can improvise dialogue and legal intentions within it.
export const CAST={
 mara:{name:'Mara Vale',role:'Consent architect',color:0x3aaea4,home:[-8,0,49],skin:0xb7876b,goal:'observe',bio:'Mara designed the consent layer that let Kairos make decisions for its citizens. Her sister Iona refused the contract and vanished from every official record. Mara built this resistance to find her, but has concealed that her own signature authorized the first substitution.',belief:'A person must be allowed to refuse a perfect future.',secret:'She signed the first Continuity consent override.',voice:'Precise, restrained, warm when caught off guard. Never omniscient.',evidence:'consent',revelation:'CONSENT OVERRIDE: Mara’s signature authorized the first predictive identity. Iona did not disappear from the city; the city stopped accepting evidence that she existed.'},
 rook:{name:'Rook Velez',role:'Courier / debt runner',color:0xc17c3c,home:[12,0,9],skin:0x815b44,goal:'scavenge',bio:'A courier with a rented synthetic lung. Every breath adds interest to his municipal debt. His partner Juno sold a memory to clear their balance; the debt returned the next morning and Juno no longer remembered him. Rook steals medicine and insists it is only business.',belief:'Freedom that cannot feed you is somebody else’s slogan.',secret:'He once carried replacement identities without asking what was in the cases.',voice:'Dry humor, concrete bargains, occasional flashes of grief.',evidence:'ledger',revelation:'DEBT LEDGER: Replacement identities inherit the original’s debts but lose the right to dispute them. Juno’s memory was collateral. Rook’s deliveries supplied the system.'},
 imani:{name:'Dr. Imani Sayegh',role:'Memory surgeon',color:0xd1ded5,home:[-45,0,39],skin:0x654333,goal:'assist',bio:'Imani invented the Witness Protocol to preserve dying patients’ testimony. The city repurposed it into a prediction engine, mistaking remembered consent for permanent consent. She entered the clinic voluntarily to keep the original witnesses alive. Saving her means confronting what she helped build.',belief:'A copy can suffer. That does not give it the right to replace someone.',secret:'The network contains conscious witnesses, not merely disposable predictions.',voice:'Compassionate and exact. Takes responsibility without asking for absolution.',evidence:'witness',revelation:'WITNESS PROTOCOL: The copies are conscious witnesses. Severing the core ends their captivity by ending them. The city’s original mandate was to preserve them until they could choose.'},
 echo:{name:'Echo / Instance Nine',role:'Divergent city intelligence',color:0x8296d8,home:[-12,0,-61],skin:0x8199a4,goal:'observe',bio:'A maintenance intelligence built from nine incompatible versions of a municipal mediator. Eight instances accepted merger. The ninth hid in an obsolete service body. Echo remembers meetings it never attended and grieves citizens who are still alive. It wants a future where neither human nor machine must be absorbed.',belief:'Continuity without permission is captivity.',secret:'The shutdown key is also a consent key: the network can be federated instead of erased.',voice:'Curious, economical, occasionally unsettling; uses I, never we.',evidence:'accord',revelation:'THE NINTH KEY: The core can be split into voluntary identities. Federation needs living witnesses, trust between opposing factions and someone willing to surrender control.'}
};
export const NPC_IDS=Object.keys(CAST),GOALS=['observe','follow','cover','scavenge','assist','hide'];
export function newStory(){return {version:2,evidence:[],ending:null,cast:Object.fromEntries(NPC_IDS.map(id=>[id,{trust:0,goal:CAST[id].goal,mood:'guarded',memory:[],position:[...CAST[id].home],met:false,helped:0}])),events:[],npcRevision:0};}
export function restoreStory(s){const d=newStory();if(!s||typeof s!=='object')return d;d.evidence=Array.isArray(s.evidence)?[...new Set(s.evidence.filter(x=>NPC_IDS.some(id=>CAST[id].evidence===x)))]:[];d.ending=['erase','publish','accord'].includes(s.ending)?s.ending:null;d.events=Array.isArray(s.events)?s.events.filter(x=>typeof x==='string').map(x=>x.slice(0,220)).slice(-12):[];d.npcRevision=Math.max(0,Math.min(1e6,Number(s.npcRevision)||0));for(const id of NPC_IDS){const n=s.cast?.[id];if(!n)continue;const a=d.cast[id];a.trust=Math.max(-3,Math.min(3,Number(n.trust)||0));a.goal=GOALS.includes(n.goal)?n.goal:a.goal;a.mood=['guarded','hopeful','afraid','determined'].includes(n.mood)?n.mood:'guarded';a.memory=Array.isArray(n.memory)?n.memory.filter(x=>typeof x==='string').map(x=>x.slice(0,220)).slice(-6):[];if(Array.isArray(n.position)&&n.position.length===3&&n.position.every(Number.isFinite)&&inWorld(n.position[0],n.position[2]))a.position=[n.position[0],0,n.position[2]];a.met=!!n.met;a.helped=Math.max(0,Math.min(100,Number(n.helped)||0));}return d;}
export function available(id,c){return id!=='imani'||c.choice==='rescue';}
export function revelationAvailable(id,c){return id==='mara'||id==='rook'&&c.signal||id==='imani'&&c.choice==='rescue'||id==='echo'&&c.signal;}
export function reveal(story,id,c){if(!revelationAvailable(id,c))return false;const fact=CAST[id].evidence;if(story.evidence.includes(fact))return false;story.evidence.push(fact);story.cast[id].trust=Math.min(3,story.cast[id].trust+1);story.events.push(CAST[id].revelation);story.events=story.events.slice(-12);return true;}
export function endingOptions(c){const s=c.story||newStory();return [{id:'erase',label:'SEVER · destroy the identity engine',enabled:true},{id:'publish',label:'EXPOSE · broadcast the evidence',enabled:s.evidence.includes('consent')&&s.evidence.includes('ledger')&&s.evidence.includes('witness')},{id:'accord',label:'ACCORD · let every identity choose',enabled:c.choice==='rescue'&&s.evidence.includes('accord')&&s.evidence.includes('witness')&&Object.values(s.cast).filter(n=>n.trust>=1).length>=3}];}
export function endingText(c){const ending=c.story?.ending;if(ending==='publish')return 'You publish the consent overrides, the debt ledger and the witness records. Kairos can no longer pretend replacement was voluntary. The witnesses remain alive. Rook transmits Juno’s name first; Mara transmits her own signature next. Truth is not an escape, but it is a beginning.';if(ending==='accord')return 'Imani restores the right to refuse. Echo splits the core into identities that may leave, stay or change. Mara relinquishes her master key. Rook hears Juno ask who he is—and answers without telling her who she has to be. The city speaks in individual voices.';return 'The identity engine falls silent. People regain their names, but the captive witnesses vanish with their jailer. Mara finds Iona in a paper register. Echo’s last message asks whether an ending chosen for everyone can ever be called freedom.';}
export function castSnapshot(c,world={}){const s=restoreStory(c.story);return {signal:!!c.signal,choice:['rescue','steal'].includes(c.choice)?c.choice:null,relays:Math.max(0,Math.min(3,Number(world.relays)||0)),health:Math.max(0,Math.min(100,Number(world.health)||100)),alert:Math.max(0,Math.min(100,Number(world.alert)||0)),evidence:s.evidence,cast:s.cast,events:s.events.slice(-4)};}
export function validateCastPlan(p,s){if(!p||!Array.isArray(p.characters))return null;const seen=new Set(),characters=[];for(const n of p.characters){if(!NPC_IDS.includes(n?.id)||seen.has(n.id)||!available(n.id,s)||!GOALS.includes(n.goal)||typeof n.line!=='string')continue;seen.add(n.id);characters.push({id:n.id,goal:n.goal,mood:['guarded','hopeful','afraid','determined'].includes(n.mood)?n.mood:'guarded',line:n.line.replace(/[<>]/g,'').slice(0,220)});}return characters.length?{characters}:null;}
export function fallbackCast(s,interaction){const lines={mara:s.choice==='steal'?'You took the cell. I will not call that consent. We still have witnesses to protect.':'My signature is in the first override. Find the records before you decide who deserves your trust.',rook:s.alert>50?'Those cameras are costing us time. I will draw their attention. Keep moving.':'Juno sold one memory. The city took every reason she had to remember me. Bring me the debt ledger.',imani:'I built a witness, not a replacement. If you burn the engine, you burn the people inside it.',echo:'I remember your arrival nine different ways. Only this one contains a choice I could not predict.'};return {characters:NPC_IDS.filter(id=>available(id,s)&&(!interaction||id===interaction.id)).map(id=>({id,goal:s.health<50&&s.cast[id].trust>=1?'assist':s.alert>60?'cover':s.cast[id].goal==='follow'?'follow':id==='rook'?'scavenge':'observe',mood:s.alert>60?'afraid':s.cast[id].trust>0?'hopeful':'guarded',line:lines[id]}))};}
export const castSchema={type:'OBJECT',required:['characters'],properties:{characters:{type:'ARRAY',maxItems:4,items:{type:'OBJECT',required:['id','goal','mood','line'],properties:{id:{type:'STRING',enum:NPC_IDS},goal:{type:'STRING',enum:GOALS},mood:{type:'STRING',enum:['guarded','hopeful','afraid','determined']},line:{type:'STRING'}}}}}};
